version: '3.1'

volumes:
  pg_bot_db:

services:
  pg_bot_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASS = root
      - POSTGRES_DB = test_bot
    volumes:
      - pg_bot_db
    ports:
      - "5432:5432"

  app:
    restart: always
    build: .
    ports:
      - 8080:8080
    depends_on:
      - pg_bot_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://pg_bot_db:5432/test_bot'