
spring:
  application:
    name: testbot
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/test_bot
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true