package com.testtaskbot.model.enums;

public enum ChatState {
    CONFIRMATION_DATA_PROCESSING,
    START,
    ENTER_NAME,
    ENTER_SURNAME,
    ENTER_PHONE,
    ENTER_ADDRESS,
    CONFIRM_DATA,
    SEND_SURNAME, SEND_BIRTH_DATE, ENTER_BIRTH_DATE, ENTER_SEX, SEND_PHOTO, ENTER_PHOTO, SAVE_USER, FINISHED
}
